// <auto-generated />
using System;
using GraphQLPlayground.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20190723183209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GraphQLPlayground.Core.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulbasaur"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ivysaur"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venusaur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Charmander"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charmeleon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charizard"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Squirtle"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wartortle"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Blastoise"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Caterpie"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Metapod"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Butterfree"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Weedle"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kakuna"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Beedrill"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Pidgey"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pidgeotto"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pidgeot"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rattata"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Raticate"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Spearow"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Fearow"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ekans"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Arbok"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Pikachu"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Raichu"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sandshrew"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Sandslash"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Nidoran"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Nidorina"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Nidoqueen"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Nidoran"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Nidorino"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Nidoking"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Clefairy"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Clefable"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Vulpix"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ninetales"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Jigglypuff"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Wigglytuff"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Zubat"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Golbat"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Oddish"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Gloom"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Vileplume"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Paras"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Parasect"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Venonat"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Venomoth"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Diglett"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Dugtrio"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Meowth"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Persian"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Psyduck"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Golduck"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Mankey"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Primeape"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Growlithe"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Arcanine"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Poliwag"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Poliwhirl"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Poliwrath"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Abra"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Kadabra"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Alakazam"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Machop"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Machoke"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Machamp"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Bellsprout"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Weepinbell"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Victreebel"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Tentacool"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Tentacruel"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Geodude"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Graveler"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Golem"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Ponyta"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Rapidash"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Slowpoke"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Slowbro"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Magnemite"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Magneton"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Farfetch"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Doduo"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Dodrio"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Seel"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Dewgong"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Grimer"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Muk"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Shellder"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Cloyster"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Gastly"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Haunter"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Gengar"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Onix"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Drowzee"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Hypno"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Krabby"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Kingler"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Voltorb"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Electrode"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Exeggcute"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Exeggutor"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Cubone"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Marowak"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Hitmonlee"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Hitmonchan"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Lickitung"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Koffing"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Weezing"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Rhyhorn"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Rhydon"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Chansey"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Tangela"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Kangaskhan"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Horsea"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Seadra"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Goldeen"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Seaking"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Staryu"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Starmie"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Mr"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Scyther"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Jynx"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Electabuzz"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Magmar"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Pinsir"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Tauros"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Magikarp"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Gyarados"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Lapras"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Ditto"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Eevee"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Vaporeon"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Jolteon"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Flareon"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Porygon"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Omanyte"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Omastar"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Kabuto"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Kabutops"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Aerodactyl"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Snorlax"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Articuno"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Zapdos"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Moltres"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Dratini"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Dragonair"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Dragonite"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Mewtwo"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Mew"
                        });
                });

            modelBuilder.Entity("GraphQLPlayground.Core.Models.PokemonType", b =>
                {
                    b.Property<int>("PokemonId");

                    b.Property<int>("TypeId");

                    b.Property<int?>("PokemonId1");

                    b.Property<int?>("TypeId1");

                    b.HasKey("PokemonId", "TypeId");

                    b.HasIndex("PokemonId1");

                    b.HasIndex("TypeId");

                    b.HasIndex("TypeId1");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 1,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 2,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 2,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 3,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 3,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 4,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 5,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 6,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 7,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 8,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 9,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 10,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 11,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 12,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 12,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 13,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 13,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 14,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 14,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 15,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 15,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 16,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 16,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 17,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 17,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 18,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 18,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 19,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 20,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 21,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 21,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 22,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 22,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 23,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 24,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 25,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 26,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 27,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 28,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 29,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 30,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 31,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 31,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 32,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 33,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 34,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 34,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 35,
                            TypeId = 4
                        },
                        new
                        {
                            PokemonId = 36,
                            TypeId = 4
                        },
                        new
                        {
                            PokemonId = 37,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 38,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 39,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 39,
                            TypeId = 4
                        },
                        new
                        {
                            PokemonId = 40,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 40,
                            TypeId = 4
                        },
                        new
                        {
                            PokemonId = 41,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 41,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 42,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 42,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 43,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 43,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 44,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 44,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 45,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 45,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 46,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 46,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 47,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 47,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 48,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 48,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 49,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 49,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 50,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 51,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 52,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 53,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 54,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 55,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 56,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 57,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 58,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 59,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 60,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 61,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 62,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 62,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 63,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 64,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 65,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 66,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 67,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 68,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 69,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 69,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 70,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 70,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 71,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 71,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 72,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 72,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 73,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 73,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 74,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 74,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 75,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 75,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 76,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 76,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 77,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 78,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 79,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 79,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 80,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 80,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 81,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 81,
                            TypeId = 16
                        },
                        new
                        {
                            PokemonId = 82,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 82,
                            TypeId = 16
                        },
                        new
                        {
                            PokemonId = 83,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 83,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 84,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 84,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 85,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 85,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 86,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 87,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 87,
                            TypeId = 11
                        },
                        new
                        {
                            PokemonId = 88,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 89,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 90,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 91,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 91,
                            TypeId = 11
                        },
                        new
                        {
                            PokemonId = 92,
                            TypeId = 8
                        },
                        new
                        {
                            PokemonId = 92,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 93,
                            TypeId = 8
                        },
                        new
                        {
                            PokemonId = 93,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 94,
                            TypeId = 8
                        },
                        new
                        {
                            PokemonId = 94,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 95,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 95,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 96,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 97,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 98,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 99,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 100,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 101,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 102,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 102,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 103,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 103,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 104,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 105,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 106,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 107,
                            TypeId = 5
                        },
                        new
                        {
                            PokemonId = 108,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 109,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 110,
                            TypeId = 13
                        },
                        new
                        {
                            PokemonId = 111,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 111,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 112,
                            TypeId = 10
                        },
                        new
                        {
                            PokemonId = 112,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 113,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 114,
                            TypeId = 9
                        },
                        new
                        {
                            PokemonId = 115,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 116,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 117,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 118,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 119,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 120,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 121,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 121,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 122,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 122,
                            TypeId = 4
                        },
                        new
                        {
                            PokemonId = 123,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 123,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 124,
                            TypeId = 11
                        },
                        new
                        {
                            PokemonId = 124,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 125,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 126,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 127,
                            TypeId = 1
                        },
                        new
                        {
                            PokemonId = 128,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 129,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 130,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 130,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 131,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 131,
                            TypeId = 11
                        },
                        new
                        {
                            PokemonId = 132,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 133,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 134,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 135,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 136,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 137,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 138,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 138,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 139,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 139,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 140,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 140,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 141,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 141,
                            TypeId = 17
                        },
                        new
                        {
                            PokemonId = 142,
                            TypeId = 15
                        },
                        new
                        {
                            PokemonId = 142,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 143,
                            TypeId = 12
                        },
                        new
                        {
                            PokemonId = 144,
                            TypeId = 11
                        },
                        new
                        {
                            PokemonId = 144,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 145,
                            TypeId = 3
                        },
                        new
                        {
                            PokemonId = 145,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 146,
                            TypeId = 6
                        },
                        new
                        {
                            PokemonId = 146,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 147,
                            TypeId = 2
                        },
                        new
                        {
                            PokemonId = 148,
                            TypeId = 2
                        },
                        new
                        {
                            PokemonId = 149,
                            TypeId = 2
                        },
                        new
                        {
                            PokemonId = 149,
                            TypeId = 7
                        },
                        new
                        {
                            PokemonId = 150,
                            TypeId = 14
                        },
                        new
                        {
                            PokemonId = 151,
                            TypeId = 14
                        });
                });

            modelBuilder.Entity("GraphQLPlayground.Core.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bug"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fairy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ground"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Water"
                        });
                });

            modelBuilder.Entity("GraphQLPlayground.Core.Models.PokemonType", b =>
                {
                    b.HasOne("GraphQLPlayground.Core.Models.Pokemon")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GraphQLPlayground.Core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId1");

                    b.HasOne("GraphQLPlayground.Core.Models.Type")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GraphQLPlayground.Core.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId1");
                });
#pragma warning restore 612, 618
        }
    }
}
